services:
  wp:
    image: intellisrc/wp-litespeed-alpine:edge
    volumes:
      - type: bind
        source: "/docker/sites/example/"
        target: "/var/www/wp-content/"
    networks:
      - proxy_net
      - database_net
    environment:
      DB_HOST: database_host
      DB_USER: example_user
      DB_NAME: wp_example
      DB_PASS: *****************
      WP_PREFIX: ex_
      HTTPS_DOMAIN: example.com
      LS_SOFT_LIMIT: 512M
      LS_HARD_LIMIT: 700M
      OBJ_CACHE: memcached
      #WP_LANG: ja
    healthcheck:
      test: wget -q -O - http://localhost/health_check.php | grep "ok"
      interval: 60s
      retries: 2
      timeout: 30s
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints: 
          - node.labels.wordpress == true
